# Module Import Test Notebook

This notebook validates that the refactored modules load correctly.

In [1]:
#========================================
# Setup paths and notebook defaults
#========================================
from pathlib import Path
import sys

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as pp
import seaborn as sns

BASE_DIR = Path.cwd().resolve().parent
DATA_DIR = BASE_DIR / "data"
INPUT_DIR = DATA_DIR / "input"


if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

print(f"BASE_DIR: {BASE_DIR}")

BASE_DIR: C:\Users\F.Turner\Documents\MwM Proof of Concept V2

In [2]:
from src.ingest import *
from src.aggregate import *
from src.combine import *
from src.output import *

print("Imports succeeded: ingest.py, aggregate.py, combine.py, and output.py are available.")

Imports succeeded: ingest.py, aggregate.py, combine.py, and output.py are available.

In [3]:
df = pd.read_csv(DATA_DIR / "output" / "kenya" / "tables" / "combined_child_level.csv")

In [4]:
df

,date_time,admin1,admin2,admin3,school,sex,age,grade,age_group,haldo_sel,haldo_literacy,_uuid,location,protection_status,disability,round,aser_literacy,aser_numeracy
0,2023-06-12,8,800.0,80005.0,school01,1,7.0,0.0,6-10,0.604167,0.175000,1923914235876098121,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-06-12,8,800.0,80005.0,school02,1,7.0,0.0,6-10,0.604167,0.175000,14316521119066352241,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-06-07,9,902.0,90201.0,school03,1,7.0,2.0,6-10,0.837500,0.431818,8029136157369546520,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-06-07,9,902.0,90201.0,school04,1,7.0,1.0,6-10,0.437500,0.431818,10855389975063662343,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-06-08,9,902.0,90203.0,school05,1,8.0,0.0,6-10,0.500000,0.150000,17252436797090343061,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1461,2023-06-13,NaN,NaN,community4,school07,2,NaN,NaN,NaN,NaN,NaN,db9a6281-3825-4993-b9b3-76117e5fd0c0,NaN,NaN,NaN,NaN,NaN,NaN
1462,2023-06-13,NaN,NaN,community5,school08,3,NaN,NaN,NaN,NaN,NaN,07170e16-37fb-4a65-ae2b-fbe97d8a96e7,NaN,NaN,NaN,NaN,NaN,NaN
1463,2023-06-13,NaN,NaN,community5,school09,3,NaN,NaN,NaN,NaN,NaN,435e01cb-dc87-459e-b2da-bfd33087ef29,NaN,NaN,NaN,NaN,NaN,NaN
1464,2023-06-13,NaN,NaN,community5,school01,3,NaN,NaN,NaN,NaN,NaN,cf51583a-a512-4f2d-ac28-9b83162763d5,NaN,NaN,NaN,NaN,NaN,NaN
1465,2023-06-13,NaN,NaN,community5,school02,2,NaN,NaN,NaN,NaN,NaN,df0a3dba-d79c-4d00-9473-b60f635b4508,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
ds_obs = build_dataset(file_path=str(INPUT_DIR / "lesson_obs.xlsx"))
ds_obs = aggregates(ds_obs)
combined = add_to_combined(ds_obs, output_dir=BASE_DIR / "data" / "output")

KeyboardInterrupt: Interrupted by user

In [ ]:
ds_aser = build_dataset(file_path=str(INPUT_DIR / "aser_sample.csv"))
ds_aser = aggregates(ds_aser)
combined_aser = add_to_combined(ds_aser, output_dir=BASE_DIR / "data" / "output")

Form ID aser_001 already exists in the log. Processed data will be added to the existing dataset.
Metadata added to log:
{'form_id': 'aser_001', 'survey_name': 'aser_assessment', 'level': 'child', 'first_submission': '01/01/2026 00:00', 'last_submission': '03/01/2026 00:00', 'rows': 200, 'country': 'kenya', '_uuid_cols': 'child_uid,school_name,child_age'}
Data imported from file. Kobo metadata functions will be skipped (question dataframe and choices dataframe). Only basic metadata will be logged.
Dropped columns: ['child_name'] to protect child privacy
Using previously logged hash columns for UUID generation: ['child_uid', 'school_name', 'child_age']
Available dimensions: ['date_time', 'admin1', 'location', 'protection_status', 'school', 'sex', 'age', 'disability', 'round', 'age_group']
Missing dimensions: ['admin0', 'admin2', 'admin3', 'grade']
Resolved columns: {'date_time': '_submission_time', 'admin0': None, 'admin1': 'region', 'admin2': None, 'admin3': None, 'location': 'location', 'protection_status': 'protection_status', 'school': 'school_name', 'sex': 'child_sex', 'age': 'child_age', 'disability': 'disability_status', 'grade': None, 'round': 'round', 'age_group': 'child_age'}
Derived dimensions computed: ['age_group']
Available indicators: ['aser_literacy', 'aser_numeracy']
Missing indicators: ['haldo_self_concept', 'haldo_empathy', 'haldo_expressive_language', 'haldo_letter_identification', 'haldo_accuracy', 'haldo_comprehension', 'haldo_sel', 'haldo_literacy']

In [ ]:
ds_haldo = build_dataset(file_path=str(INPUT_DIR / "haldo_sample.xlsx"))
ds_haldo = aggregates(ds_haldo)
combined_haldo = add_to_combined(ds_haldo, output_dir=BASE_DIR / "data" / "output")

C:\Users\F.Turner\Documents\MwM Proof of Concept V2\src\ingest.py:286: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  country = None

Form ID haldo_001 already exists in the log. Processed data will be added to the existing dataset.
Metadata added to log:
{'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'rows': 1246, 'country': 'kenya', '_uuid_cols': 'start,end,childid'}
Data imported from file. Kobo metadata functions will be skipped (question dataframe and choices dataframe). Only basic metadata will be logged.
Using previously logged hash columns for UUID generation: ['start', 'end', 'childid']
Available dimensions: ['date_time', 'admin1', 'admin2', 'admin3', 'school', 'sex', 'age', 'grade', 'age_group']
Missing dimensions: ['admin0', 'location', 'protection_status', 'disability', 'round']
Resolved columns: {'date_time': '_submission_time', 'admin0': None, 'admin1': 'governorate', 'admin2': 'district', 'admin3': 'subdistrict', 'location': None, 'protection_status': None, 'school': 'school', 'sex': 'sex', 'age': 'age', 'disability': None, 'grade': 'grade', 'round': None, 'age_group': 'age'}
Derived dimensions computed: ['age_group']
Available indicators: ['haldo_sel', 'haldo_literacy']
Missing indicators: ['aser_literacy', 'aser_numeracy']

In [ ]:
ds_school = build_dataset(file_path=str(INPUT_DIR / "school_sample.csv"))
ds_school = aggregates(ds_school)
ds_school_combined = school_combined(ds_school, output_dir=BASE_DIR / "data" / "output")

Form ID school_001 added to log. Processed data will be saved as a new file.
Metadata added to log:
{'form_id': 'school_001', 'survey_name': 'school_summary', 'level': 'school', 'first_submission': Timestamp('2026-01-01 00:00:00'), 'last_submission': Timestamp('2026-03-01 00:00:00'), 'rows': 27, 'country': 'kenya', '_uuid_cols': None}
Data imported from file. Kobo metadata functions will be skipped (question dataframe and choices dataframe). Only basic metadata will be logged.
UID depends on 7 columns - may be unstable
Available dimensions: ['date_time', 'admin1', 'admin2', 'school']
Missing dimensions: ['admin0', 'admin3', 'location', 'protection_status', 'sex', 'age', 'disability', 'grade', 'round', 'age_group']
Resolved columns: {'date_time': '_submission_time', 'admin0': None, 'admin1': 'region', 'admin2': 'district', 'admin3': None, 'location': None, 'protection_status': None, 'school': 'school_name', 'sex': None, 'age': None, 'disability': None, 'grade': None, 'round': None, 'age_group': None}
Derived dimensions computed: []
Available indicators: ['pta_active', 'school_management_committee_active', 'plc_frequency', 'safeguarding_policy']
Missing indicators: []

C:\Users\F.Turner\Documents\MwM Proof of Concept V2\src\combine.py:251: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  .groupby(["school", teacher_combined["date_time"].dt.to_period("M")], dropna=False)

In [ ]:
ds_school_combined.df_short.head(30)

,school,date_time,admin1,admin2,pta_active,pta_active,school_management_committee_active,plc_frequency,plc_frequency,safeguarding_policy,...,disruption_level,literacy_practice,numeracy_practice,sel_practice,student_teacher_ratio,learning_resources,gender_responsiveness,safe_environment,rtl_use,lesson_preparedness
0,school01,NaT,West,Zeta,no,no,yes,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,school01,2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000000,1.666667,2.0,1.666667,3.000000,2.333333,2.333333,2.666667,2.333333,2.333333
2,school01,2026-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,school02,NaT,West,Delta,no,no,yes,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,school02,2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.333333,2.333333,3.0,2.333333,2.666667,1.666667,2.666667,1.666667,2.333333,2.666667
5,school02,2026-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,school03,NaT,East,Gamma,yes,yes,no,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,school03,2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.500000,1.500000,3.0,2.000000,1.000000,2.000000,2.500000,3.000000,3.000000,2.000000
8,school03,2026-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,school04,NaT,South,Alpha,yes,yes,yes,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,school04,2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.500000,3.000000,2.5,1.000000,2.000000,2.500000,2.500000,1.000000,2.000000,3.000000
11,school04,2026-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,school05,NaT,East,Epsilon,no,no,no,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,school05,2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000000,1.000000,2.0,2.000000,2.000000,1.000000,3.000000,3.000000,3.000000,2.000000
14,school05,2024-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000000,3.000000,2.0,1.000000,3.000000,2.000000,3.000000,3.000000,3.000000,3.000000
15,school05,2026-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,school06,NaT,East,Zeta,yes,yes,yes,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,school06,2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.500000,1.500000,1.5,1.000000,3.000000,2.500000,2.500000,2.500000,3.000000,2.500000
18,school06,2026-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,school07,NaT,East,Delta,yes,yes,yes,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,school07,2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000000,1.000000,2.5,2.500000,1.000000,3.000000,2.000000,2.000000,3.000000,2.500000
21,school07,2026-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,school08,NaT,North,Epsilon,no,no,yes,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,school08,2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000,1.000000,2.0,2.000000,3.000000,3.000000,3.000000,2.000000,2.500000,3.000000
24,school08,2026-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,school09,NaT,West,Delta,yes,yes,no,3.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,school09,2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.500000,1.500000,2.0,1.000000,3.000000,2.500000,2.000000,3.000000,2.500000,2.000000
27,school09,2026-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Targeted Optimisation Plan

Cache config classification lookups (highest ROI, lowest risk)
Problem: each chart pair calls classification twice, and each call re-opens JSON files in report.py:55 and report.py:57, triggered from app.py:94 and app.py:95.
Change: load config once per level via cached helper (for example with st.cache_data) and classify using in-memory dicts.
Impact: removes repeated disk I/O across every rerun and every indicator-dimension pair.

Render only the currently selected level, not all three
Problem: all three tabs execute render paths in app.py:131, so one filter change recalculates Child + Teacher + School.
Change: replace level tabs with a level selector, or gate computation so only the active level runs.
Impact: often cuts dashboard compute by about 2/3 on each interaction.

Add a chart cap per indicator and lazy detail expansion
Problem: nested loops in app.py:83 and app.py:87 can generate many figures.
Change: show top N dimensions by default (for example 4-6), with an expander for “show all dimensions”.
Impact: large drop in Plotly construction/serialization time while preserving full detail on demand.

Precompute filtered dimension options once per rerun
Problem: option extraction and sorting in app.py:75 runs for each dimension every rerun.
Change: build an options map once from base df (or cached by country/level), then reuse in multiselects.
Impact: improves sidebar responsiveness, especially with high-cardinality columns.

Avoid repeated dataframe copies in hot loops
Problem: repeated slicing/copy/dropna in app.py:90 and conversion blocks around app.py:98 and app.py:116.
Change: do type normalization once per level before chart loops, and avoid unnecessary copy() unless mutation is required.
Impact: reduces memory churn and Python overhead.

Cache figure-ready aggregates for common plot paths
Problem: repeated groupby and crosstab in report.py:192, report.py:199, report.py:219.
Change: cache grouped outputs keyed by (country, level, indicator, dimension, filter_signature).
Impact: big gains when users tweak a subset of filters repeatedly.

Reduce per-figure axis/tick work
Problem: tick text rebuilding for every figure in report.py:251.
Change: only apply custom tick formatting for categorical axes with large labels; skip for numeric/clean short labels.
Impact: modest but noticeable when many charts are shown.

Keep data loading cached but tighten cache keys
Good: app.py:32 already caches load.
Improve: ensure cache depends only on (level, country) and clear cache only after ingestion (already done at app.py:184 and app.py:228).
Impact: avoids accidental unnecessary reloads.

Suggested rollout order (minimal structural change)

- Config caching in classification.
- Single active level rendering.
- Chart cap + optional “show all”.
- Loop/dataframe micro-optimizations.
- Optional aggregate caching if still slow.

How to validate each step

Add timing logs around app.py:54 and inside chart loop near app.py:87.
Track:
total rerun time
number of charts rendered
average time per chart
Compare baseline vs after each step, keeping same country/filter state.
If you want, I can draft a concrete patch plan with exact function signatures and cache-key structure before any code changes.

# **SUPABASE**

In [ ]:
pip install supabase

Collecting supabase
  Downloading supabase-2.31.0-py3-none-any.whl.metadata (4.7 kB)
Collecting realtime==2.31.0 (from supabase)
  Downloading realtime-2.31.0-py3-none-any.whl.metadata (7.0 kB)
Collecting supabase-functions==2.31.0 (from supabase)
  Downloading supabase_functions-2.31.0-py3-none-any.whl.metadata (2.4 kB)
Collecting storage3==2.31.0 (from supabase)
  Downloading storage3-2.31.0-py3-none-any.whl.metadata (2.2 kB)
Collecting supabase-auth==2.31.0 (from supabase)
  Downloading supabase_auth-2.31.0-py3-none-any.whl.metadata (6.4 kB)
Collecting postgrest==2.31.0 (from supabase)
  Downloading postgrest-2.31.0-py3-none-any.whl.metadata (3.4 kB)
Collecting httpx<0.29,>=0.26 (from supabase)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting yarl>=1.22.0 (from supabase)
  Downloading yarl-1.25.1-cp313-cp313-win_amd64.whl.metadata (115 kB)
Collecting deprecation>=2.1.0 (from postgrest==2.31.0->supabase)
  Downloading deprecation-2.1.0-py2.py3-none-any.whl.metadata (4.6 kB)
Collecting pydantic<3.0,>=1.9 (from postgrest==2.31.0->supabase)
  Downloading pydantic-2.13.5-py3-none-any.whl.metadata (110 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in c:\Users\F.Turner\Documents\MwM Proof of Concept V2\.venv\Lib\site-packages (from realtime==2.31.0->supabase) (4.15.0)
Collecting websockets<16,>=11 (from realtime==2.31.0->supabase)
  Downloading websockets-15.0.1-cp313-cp313-win_amd64.whl.metadata (7.0 kB)
Collecting pyjwt>=2.12.0 (from pyjwt[crypto]>=2.12.0->supabase-auth==2.31.0->supabase)
  Downloading pyjwt-2.15.1-py3-none-any.whl.metadata (3.5 kB)
Collecting strenum>=0.4.15 (from supabase-functions==2.31.0->supabase)
  Downloading StrEnum-0.4.15-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: anyio in c:\Users\F.Turner\Documents\MwM Proof of Concept V2\.venv\Lib\site-packages (from httpx<0.29,>=0.26->supabase) (4.13.0)
Requirement already satisfied: certifi in c:\Users\F.Turner\Documents\MwM Proof of Concept V2\.venv\Lib\site-packages (from httpx<0.29,>=0.26->supabase) (2026.5.20)
Collecting httpcore==1.* (from httpx<0.29,>=0.26->supabase)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in c:\Users\F.Turner\Documents\MwM Proof of Concept V2\.venv\Lib\site-packages (from httpx<0.29,>=0.26->supabase) (3.18)
Requirement already satisfied: h11>=0.16 in c:\Users\F.Turner\Documents\MwM Proof of Concept V2\.venv\Lib\site-packages (from httpcore==1.*->httpx<0.29,>=0.26->supabase) (0.16.0)
Collecting h2<5,>=3 (from httpx[http2]<0.29,>=0.26->postgrest==2.31.0->supabase)
  Downloading h2-4.4.1-py3-none-any.whl.metadata (3.8 kB)
Collecting hyperframe<7,>=6.1 (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.31.0->supabase)
  Downloading hyperframe-6.1.0-py3-none-any.whl.metadata (4.3 kB)
Collecting hpack<5,>=4.2 (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.31.0->supabase)
  Downloading hpack-4.2.0-py3-none-any.whl.metadata (3.3 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0,>=1.9->postgrest==2.31.0->supabase)
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.5 (from pydantic<3.0,>=1.9->postgrest==2.31.0->supabase)
  Downloading pydantic_core-2.46.5-cp313-cp313-win_amd64.whl.metadata (6.7 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0,>=1.9->postgrest==2.31.0->supabase)
  Downloading typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: packaging in c:\Users\F.Turner\Documents\MwM Proof of Concept V2\.venv\Lib\site-packages (from deprecation>=2.1.0->postgrest==2.31.0->supabase) (26.2)
Collecting cryptography>=3.4.0 (from pyjwt[crypto]>=2.12.0->supabase-auth==2.31.0->supabase)
  Downloading cryptography-50.0.2-cp311-abi3-win_amd64.whl.metadata (4.4 kB)
Collecting cffi>=2.0.0 (from cryptography>=3.4.0->pyjwt[crypto]>=2.12.0->supabase-auth==2.31.0->supabase)
  Downloading cffi-2.1.1-cp313-cp313-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography>=3.4.0->pyjwt[crypto]>=2.12.0->supabase-auth==2.31.0->supabase)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting multidict>=4.0 (from yarl>=1.22.0->supabase)
  Downloading multidict-7.0.0-cp313-cp313-win_amd64.whl.metadata (6.3 kB)
Collecting propcache>=0.2.1 (from yarl>=1.22.0->supabase)
  Downloading propcache-0.5.4-cp313-cp313-win_amd64.whl.metadata (25 kB)
Downloading supabase-2.31.0-py3-none-any.whl (16 kB)
Downloading postgrest-2.31.0-py3-none-any.whl (23 kB)
Downloading realtime-2.31.0-py3-none-any.whl (22 kB)
Downloading storage3-2.31.0-py3-none-any.whl (28 kB)
Downloading supabase_auth-2.31.0-py3-none-any.whl (48 kB)
Downloading supabase_functions-2.31.0-py3-none-any.whl (8.8 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading h2-4.4.1-py3-none-any.whl (62 kB)
Downloading hpack-4.2.0-py3-none-any.whl (34 kB)
Downloading hyperframe-6.1.0-py3-none-any.whl (13 kB)
Downloading pydantic-2.13.5-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.5-cp313-cp313-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   -------------------- ------------------- 1.0/2.0 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 5.9 MB/s  0:00:00
Downloading websockets-15.0.1-cp313-cp313-win_amd64.whl (176 kB)
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Downloading pyjwt-2.15.1-py3-none-any.whl (33 kB)
Downloading cryptography-50.0.2-cp311-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------- ----------------------------- 1.0/3.8 MB 6.1 MB/s eta 0:00:01
   ------------------------ --------------- 2.4/3.8 MB 6.1 MB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 6.0 MB/s  0:00:00
Downloading cffi-2.1.1-cp313-cp313-win_amd64.whl (185 kB)
Downloading StrEnum-0.4.15-py3-none-any.whl (8.9 kB)
Downloading typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Downloading yarl-1.25.1-cp313-cp313-win_amd64.whl (101 kB)
Downloading multidict-7.0.0-cp313-cp313-win_amd64.whl (87 kB)
Downloading propcache-0.5.4-cp313-cp313-win_amd64.whl (45 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: strenum, websockets, typing-inspection, pyjwt, pydantic-core, pycparser, propcache, multidict, hyperframe, httpcore, hpack, deprecation, annotated-types, yarl, pydantic, httpx, h2, cffi, realtime, cryptography, supabase-functions, storage3, postgrest, supabase-auth, supabase

  Attempting uninstall: websockets

    Found existing installation: websockets 16.0

    Uninstalling websockets-16.0:

      Successfully uninstalled websockets-16.0

   - --------------------------------------  1/25 [websockets]
   - --------------------------------------  1/25 [websockets]
   ---- -----------------------------------  3/25 [pyjwt]
   --------- ------------------------------  6/25 [propcache]
   -------------- -------------------------  9/25 [httpcore]
   -------------- -------------------------  9/25 [httpcore]
   ----------------- ---------------------- 11/25 [deprecation]
   -------------------- ------------------- 13/25 [yarl]
   -------------------- ------------------- 13/25 [yarl]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ---------------------- ----------------- 14/25 [pydantic]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------ --------------- 15/25 [httpx]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   ------------------------- -------------- 16/25 [h2]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   --------------------------- ------------ 17/25 [cffi]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ---------------------------- ----------- 18/25 [realtime]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]
   ------------------------------ --------- 19/25 [cryptography]

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import os
from supabase import create_client, Client

In [4]:
from dotenv import load_dotenv

load_dotenv()

True

In [5]:

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key)

In [6]:
from supabase import create_client
from dotenv import load_dotenv
import os

load_dotenv()

supabase = create_client(
os.getenv("SUPABASE_URL"),
os.getenv("SUPABASE_KEY")
)

print("Connected")

Connected

In [7]:
import requests

requests.get("https://www.google.com")

In [24]:
pip install python-certifi-win32

Collecting python-certifi-win32
  Using cached python_certifi_win32-1.6.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting wrapt>=1.10.4 (from python-certifi-win32)
  Downloading wrapt-2.5.0-cp313-cp313-win_amd64.whl.metadata (7.7 kB)
Requirement already satisfied: certifi in c:\Users\F.Turner\Documents\MwM Proof of Concept V2\.venv\Lib\site-packages (from python-certifi-win32) (2026.7.22)
Collecting setuptools-scm (from python-certifi-win32)
  Downloading setuptools_scm-10.3.4-py3-none-any.whl.metadata (6.7 kB)
Collecting vcs-versioning<3,>=2.5.0.dev0 (from setuptools-scm->python-certifi-win32)
  Downloading vcs_versioning-2.5.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: packaging>=20 in c:\Users\F.Turner\Documents\MwM Proof of Concept V2\.venv\Lib\site-packages (from setuptools-scm->python-certifi-win32) (26.2)
Requirement already satisfied: setuptools in c:\Users\F.Turner\Documents\MwM Proof of Concept V2\.venv\Lib\site-packages (from setuptools-scm->python-certifi-win32) (82.0.1)
Using cached python_certifi_win32-1.6.1-py2.py3-none-any.whl (7.3 kB)
Downloading wrapt-2.5.0-cp313-cp313-win_amd64.whl (105 kB)
Downloading setuptools_scm-10.3.4-py3-none-any.whl (33 kB)
Downloading vcs_versioning-2.5.0-py3-none-any.whl (122 kB)
Installing collected packages: wrapt, vcs-versioning, setuptools-scm, python-certifi-win32

   ---------- ----------------------------- 1/4 [vcs-versioning]
   ---------- ----------------------------- 1/4 [vcs-versioning]
   ---------- ----------------------------- 1/4 [vcs-versioning]
   ---------- ----------------------------- 1/4 [vcs-versioning]
   -------------------- ------------------- 2/4 [setuptools-scm]
   ---------------------------------------- 4/4 [python-certifi-win32]

Successfully installed python-certifi-win32-1.6.1 setuptools-scm-10.3.4 vcs-versioning-2.5.0 wrapt-2.5.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
from supabase import create_client

supabase = create_client(
url,
key
)


result = supabase.table("combined_school").select("*").limit(30).execute()
    
print(result)

data=[{'school': 'school01', 'date_time': None, 'admin1': 'West', 'admin2': 'Zeta', 'pta_active': 'no', 'pta_active_1': 'no', 'school_management_committee_active': 'yes', 'plc_frequency': 1, 'plc_frequency_1': 1, 'safeguarding_policy': 0, 'safeguarding_policy_1': 0, 'haldo_sel': 1.3571987864254, 'haldo_literacy': 0.447432962720732, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': '491024dc-2b93-4799-a078-53e8a0e8008e'}, {'school': 'school01', 'date_time': '2024-10', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': '1.6666666666666667', 'class_management_time': '1.6666666666666667', 'facilitation_time': '2.0', 'off_task_behaviour': '2.0', 'disruption_level': '3.0', 'literacy_practice': '1.6666666666666667', 'numeracy_practice': '2.0', 'sel_practice': '1.6666666666666667', 'student_teacher_ratio': '3.0', 'learning_resources': '2.3333333333333335', 'gender_responsiveness': '2.3333333333333335', 'safe_environment': '2.6666666666666665', 'rtl_use': '2.3333333333333335', 'lesson_preparedness': '2.3333333333333335', 'uuid': 'cec8ecde-f670-43eb-9d2f-1cfc897503c8'}, {'school': 'school01', 'date_time': '2026-01', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': '3.130434782608696', 'aser_numeracy': '1.826086956521739', 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': '2faaa6c8-728f-46f0-a0f3-fff97b65b359'}, {'school': 'school02', 'date_time': None, 'admin1': 'West', 'admin2': 'Delta', 'pta_active': 'no', 'pta_active_1': 'no', 'school_management_committee_active': 'yes', 'plc_frequency': 1, 'plc_frequency_1': 1, 'safeguarding_policy': 0, 'safeguarding_policy_1': 0, 'haldo_sel': 0.856410585817061, 'haldo_literacy': 0.434532374100719, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': 'a98ad417-8025-40ee-a8c2-e50eee14e542'}, {'school': 'school02', 'date_time': '2024-10', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': '2.3333333333333335', 'class_management_time': '2.0', 'facilitation_time': '2.0', 'off_task_behaviour': '2.0', 'disruption_level': '2.3333333333333335', 'literacy_practice': '2.3333333333333335', 'numeracy_practice': '3.0', 'sel_practice': '2.3333333333333335', 'student_teacher_ratio': '2.6666666666666665', 'learning_resources': '1.6666666666666667', 'gender_responsiveness': '2.6666666666666665', 'safe_environment': '1.6666666666666667', 'rtl_use': '2.3333333333333335', 'lesson_preparedness': '2.6666666666666665', 'uuid': '2b506254-b006-4047-9d54-978a4c895cc7'}, {'school': 'school02', 'date_time': '2026-01', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': '2.391304347826087', 'aser_numeracy': '2.347826086956522', 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': 'e3b2b083-5998-44ff-b7d1-98132f56522f'}, {'school': 'school03', 'date_time': None, 'admin1': 'East', 'admin2': 'Gamma', 'pta_active': 'yes', 'pta_active_1': 'yes', 'school_management_committee_active': 'no', 'plc_frequency': 1, 'plc_frequency_1': 1, 'safeguarding_policy': 1, 'safeguarding_policy_1': 1, 'haldo_sel': 0.862560211571003, 'haldo_literacy': 0.452419882275997, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': '7c185b8b-7b8a-4c82-a851-bb4c25eead2d'}, {'school': 'school03', 'date_time': '2024-10', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': '3.0', 'class_management_time': '2.0', 'facilitation_time': '3.0', 'off_task_behaviour': '2.5', 'disruption_level': '2.5', 'literacy_practice': '1.5', 'numeracy_practice': '3.0', 'sel_practice': '2.0', 'student_teacher_ratio': '1.0', 'learning_resources': '2.0', 'gender_responsiveness': '2.5', 'safe_environment': '3.0', 'rtl_use': '3.0', 'lesson_preparedness': '2.0', 'uuid': '544b5493-5be2-47c5-90c3-745145f87bfe'}, {'school': 'school03', 'date_time': '2026-01', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': '2.6363636363636362', 'aser_numeracy': '1.5454545454545454', 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': 'a523361d-8386-4e6f-93c8-669b3b53276c'}, {'school': 'school04', 'date_time': None, 'admin1': 'South', 'admin2': 'Alpha', 'pta_active': 'yes', 'pta_active_1': 'yes', 'school_management_committee_active': 'yes', 'plc_frequency': 1, 'plc_frequency_1': 1, 'safeguarding_policy': 1, 'safeguarding_policy_1': 1, 'haldo_sel': 2.06838360480447, 'haldo_literacy': 0.455591890124264, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': 'bf2a6e5e-539c-4ce1-b639-3e70be02d5bd'}, {'school': 'school04', 'date_time': '2024-10', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': '2.0', 'class_management_time': '2.0', 'facilitation_time': '3.0', 'off_task_behaviour': '2.5', 'disruption_level': '2.5', 'literacy_practice': '3.0', 'numeracy_practice': '2.5', 'sel_practice': '1.0', 'student_teacher_ratio': '2.0', 'learning_resources': '2.5', 'gender_responsiveness': '2.5', 'safe_environment': '1.0', 'rtl_use': '2.0', 'lesson_preparedness': '3.0', 'uuid': '4b5a1fff-2d18-49a8-9d77-c1f609427009'}, {'school': 'school04', 'date_time': '2026-01', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': '2.8181818181818183', 'aser_numeracy': '1.7272727272727273', 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': 'be4129e7-3e39-4b50-ad5a-5c65db497200'}, {'school': 'school05', 'date_time': None, 'admin1': 'East', 'admin2': 'Epsilon', 'pta_active': 'no', 'pta_active_1': 'no', 'school_management_committee_active': 'no', 'plc_frequency': 1, 'plc_frequency_1': 1, 'safeguarding_policy': 1, 'safeguarding_policy_1': 1, 'haldo_sel': 0.835226880607315, 'haldo_literacy': 0.424538866930171, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': '3bf35cc0-0327-4ede-aaa6-5e32488a1986'}, {'school': 'school05', 'date_time': '2024-10', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': '1.0', 'class_management_time': '1.0', 'facilitation_time': '2.0', 'off_task_behaviour': '3.0', 'disruption_level': '3.0', 'literacy_practice': '1.0', 'numeracy_practice': '2.0', 'sel_practice': '2.0', 'student_teacher_ratio': '2.0', 'learning_resources': '1.0', 'gender_responsiveness': '3.0', 'safe_environment': '3.0', 'rtl_use': '3.0', 'lesson_preparedness': '2.0', 'uuid': '105dc616-2bd0-4e87-bcea-13b6aeffab00'}, {'school': 'school05', 'date_time': '2024-11', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': '3.0', 'class_management_time': '2.0', 'facilitation_time': '2.0', 'off_task_behaviour': '1.0', 'disruption_level': '3.0', 'literacy_practice': '3.0', 'numeracy_practice': '2.0', 'sel_practice': '1.0', 'student_teacher_ratio': '3.0', 'learning_resources': '2.0', 'gender_responsiveness': '3.0', 'safe_environment': '3.0', 'rtl_use': '3.0', 'lesson_preparedness': '3.0', 'uuid': '44deb05b-e649-4985-b66d-be57508703cc'}, {'school': 'school05', 'date_time': '2026-01', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': '2.3181818181818183', 'aser_numeracy': '1.7727272727272727', 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': '21008f93-9063-4c68-90a5-69d60e132ec9'}, {'school': 'school06', 'date_time': None, 'admin1': 'East', 'admin2': 'Zeta', 'pta_active': 'yes', 'pta_active_1': 'yes', 'school_management_committee_active': 'yes', 'plc_frequency': 1, 'plc_frequency_1': 1, 'safeguarding_policy': 0, 'safeguarding_policy_1': 0, 'haldo_sel': 1.94731907585168, 'haldo_literacy': 0.445586297760211, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': 'eeacd05e-8a2d-4236-9d48-9d2e01190541'}, {'school': 'school06', 'date_time': '2024-10', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': '2.0', 'class_management_time': '1.5', 'facilitation_time': '2.5', 'off_task_behaviour': '2.5', 'disruption_level': '2.5', 'literacy_practice': '1.5', 'numeracy_practice': '1.5', 'sel_practice': '1.0', 'student_teacher_ratio': '3.0', 'learning_resources': '2.5', 'gender_responsiveness': '2.5', 'safe_environment': '2.5', 'rtl_use': '3.0', 'lesson_preparedness': '2.5', 'uuid': '926edb24-484c-4bca-8205-c45cc3d34222'}, {'school': 'school06', 'date_time': '2026-01', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': '2.3181818181818183', 'aser_numeracy': '2.272727272727273', 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': '2f0702a7-cd3b-496e-acd2-f3e0af9d16f5'}, {'school': 'school07', 'date_time': None, 'admin1': 'East', 'admin2': 'Delta', 'pta_active': 'yes', 'pta_active_1': 'yes', 'school_management_committee_active': 'yes', 'plc_frequency': 1, 'plc_frequency_1': 1, 'safeguarding_policy': 0, 'safeguarding_policy_1': 0, 'haldo_sel': 1.77004974695192, 'haldo_literacy': 0.443181818181818, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': 'bb56c6c9-a5a6-4e67-b2b9-15650900a891'}, {'school': 'school07', 'date_time': '2024-10', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': '2.5', 'class_management_time': '1.0', 'facilitation_time': '3.0', 'off_task_behaviour': '3.0', 'disruption_level': '3.0', 'literacy_practice': '1.0', 'numeracy_practice': '2.5', 'sel_practice': '2.5', 'student_teacher_ratio': '1.0', 'learning_resources': '3.0', 'gender_responsiveness': '2.0', 'safe_environment': '2.0', 'rtl_use': '3.0', 'lesson_preparedness': '2.5', 'uuid': 'bd13d248-9c4e-40e0-b9dc-ba3e6a87d402'}, {'school': 'school07', 'date_time': '2026-01', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': '2.909090909090909', 'aser_numeracy': '2.4545454545454546', 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': '169e44d6-801b-4adb-84e0-b4856b0d0363'}, {'school': 'school08', 'date_time': None, 'admin1': 'North', 'admin2': 'Epsilon', 'pta_active': 'no', 'pta_active_1': 'no', 'school_management_committee_active': 'yes', 'plc_frequency': 0, 'plc_frequency_1': 0, 'safeguarding_policy': 1, 'safeguarding_policy_1': 1, 'haldo_sel': 1.17120885354581, 'haldo_literacy': 0.458020421607378, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': None, 'class_management_time': None, 'facilitation_time': None, 'off_task_behaviour': None, 'disruption_level': None, 'literacy_practice': None, 'numeracy_practice': None, 'sel_practice': None, 'student_teacher_ratio': None, 'learning_resources': None, 'gender_responsiveness': None, 'safe_environment': None, 'rtl_use': None, 'lesson_preparedness': None, 'uuid': 'b78eff3e-5d54-4da0-89ff-b44174c2bd16'}, {'school': 'school08', 'date_time': '2024-10', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': None, 'aser_numeracy': None, 'time_on_task': '2.0', 'class_management_time': '2.0', 'facilitation_time': '2.5', 'off_task_behaviour': '3.0', 'disruption_level': '2.0', 'literacy_practice': '1.0', 'numeracy_practice': '2.0', 'sel_practice': '2.0', 'student_teacher_ratio': '3.0', 'learning_resources': '3.0', 'gender_responsiveness': '3.0', 'safe_environment': '2.0', 'rtl_use': '2.5', 'lesson_preparedness': '3.0', 'uuid': '4c30471e-9df9-4d9a-be06-348e754a2f03'}, {'school': 'school08', 'date_time': '2026-01', 'admin1': None, 'admin2': None, 'pta_active': None, 'pta_active_1': None, 'school_management_committee_active': None, 'plc_frequency': None, 'plc_frequency_1': None, 'safeguarding_policy': None, 'safeguarding_policy_1': None, 'haldo_sel': None, 'haldo_literacy': None, 'aser_literacy': '2.3181818181818183', 'aser_numeracy': '1.9090909090909092', 'time_on_task': None, 'class_management_time': None, 'f

In [16]:
import pandas as pd

df = pd.DataFrame(result.data)

In [17]:
df.head()

,school,date_time,admin1,admin2,pta_active,pta_active_1,school_management_committee_active,plc_frequency,plc_frequency_1,safeguarding_policy,...,literacy_practice,numeracy_practice,sel_practice,student_teacher_ratio,learning_resources,gender_responsiveness,safe_environment,rtl_use,lesson_preparedness,uuid
0,school01,NaN,West,Zeta,no,no,yes,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,491024dc-2b93-4799-a078-53e8a0e8008e
1,school01,2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.6666666666666667,2.0,1.6666666666666667,3.0,2.3333333333333335,2.3333333333333335,2.6666666666666665,2.3333333333333335,2.3333333333333335,cec8ecde-f670-43eb-9d2f-1cfc897503c8
2,school01,2026-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2faaa6c8-728f-46f0-a0f3-fff97b65b359
3,school02,NaN,West,Delta,no,no,yes,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a98ad417-8025-40ee-a8c2-e50eee14e542
4,school02,2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.3333333333333335,3.0,2.3333333333333335,2.6666666666666665,1.6666666666666667,2.6666666666666665,1.6666666666666667,2.3333333333333335,2.6666666666666665,2b506254-b006-4047-9d54-978a4c895cc7

In [35]:
df = pd.read_csv('C:\\Users\\F.Turner\\Documents\\MwM Proof of Concept V2\\data\\import_log.csv')

In [41]:
import numpy as np

In [42]:
df = df.replace({np.nan: None})

In [53]:
records = df.to_dict(
orient="records"
)

In [54]:
print(records[0])

{'form_id': 'aser_001', 'survey_name': 'aser_assessment', 'level': 'child', 'first_submission': '01/01/2026 00:00', 'last_submission': '03/01/2026 00:00', 'rows': 200, 'country': 'kenya', '_uuid_cols': 'child_uid,school_name,child_age', 'logged_at': None}

In [55]:

supabase.table(
    "import_log"
).insert(
    records
).execute()

APIResponse(data=[{'id': None, 'form_id': 'aser_001', 'survey_name': 'aser_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '01/01/2026 00:00', 'last_submission': '03/01/2026 00:00', 'logged_at': None, '_uuid_cols': 'child_uid,school_name,child_age', 'rows': 200, '_uuid': '95389960-9c16-43cf-b753-cba445e34bac'}, {'id': None, 'form_id': 'aser_001', 'survey_name': 'aser_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '01/01/2026 00:00', 'last_submission': '03/01/2026 00:00', 'logged_at': None, '_uuid_cols': 'child_uid,school_name,child_age', 'rows': 200, '_uuid': '21176788-ba21-4c5a-9739-f8c1752b4e95'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': None, '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '49e529e7-0ca8-49cb-83fa-404321517f88'}, {'id': None, 'form_id': 'school_001', 'survey_name': 'school_summary', 'level': 'school', 'country': 'kenya', 'records_imported': None, 'first_submission': '01/01/2026 00:00', 'last_submission': '01/03/2026 00:00', 'logged_at': None, '_uuid_cols': None, 'rows': 27, '_uuid': '89d93321-c284-4bc6-b840-e2493f290c71'}, {'id': None, 'form_id': 'aser_001', 'survey_name': 'aser_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '01/01/2026 00:00', 'last_submission': '03/01/2026 00:00', 'logged_at': None, '_uuid_cols': 'child_uid,school_name,child_age', 'rows': 200, '_uuid': 'ae2c0d36-db74-4c4d-98bc-6da319c60f4d'}, {'id': None, 'form_id': 'obs_001', 'survey_name': 'lesson_observation', 'level': 'teacher', 'country': 'kenya', 'records_imported': None, 'first_submission': None, 'last_submission': None, 'logged_at': '2026-06-18 09:10:00', '_uuid_cols': None, 'rows': 20, '_uuid': 'c711b141-e595-480a-81b9-eae7fa8f092f'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:29:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '10939cd6-5342-4f88-a935-a1bb6b19df02'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:30:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '49ae687e-60d2-4ba7-aadd-c38bf8896416'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:30:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '72f1e554-203a-45ae-a4d7-67045b01117e'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:34:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '3d15b940-c39e-4525-8820-f71abd08bc0c'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:36:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': 'bfa6a2f3-fcce-4013-8a7d-0737858dbcb0'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:36:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '63a62b9c-4e54-4348-b154-36854d1c7a90'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:41:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '29d327c6-215a-49be-a53a-630aade66201'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:41:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '07ff45ca-a2d6-409b-9798-7336d65cc039'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:41:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': 'f48b000d-9d71-40d3-a56b-dc529a722316'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:41:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '34cf9486-864e-408a-a2bf-fab01a0b59a2'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:42:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '1cf5e40e-bd15-40c3-8a48-15f0f3d844f3'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:42:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '5119f891-3ef6-4c3c-9a19-b7c9012d2895'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:42:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': 'ec40233c-545e-4189-bad5-26383c7b5ef8'}, {'id': None, 'form_id': 'aser_001', 'survey_name': 'aser_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '01/01/2026 00:00', 'last_submission': '03/01/2026 00:00', 'logged_at': '2026-06-18 10:43:00', '_uuid_cols': 'child_uid,school_name,child_age', 'rows': 200, '_uuid': '23e33c4e-31bc-492b-82a5-72aed5cdeb2e'}, {'id': None, 'form_id': 'aser_001', 'survey_name': 'aser_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '01/01/2026 00:00', 'last_submission': '03/01/2026 00:00', 'logged_at': '2026-06-18 10:43:00', '_uuid_cols': 'child_uid,school_name,child_age', 'rows': 200, '_uuid': '96714275-cf52-4c35-ab07-7cf156fb6e9a'}, {'id': None, 'form_id': 'aser_001', 'survey_name': 'aser_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '01/01/2026 00:00', 'last_submission': '03/01/2026 00:00', 'logged_at': '2026-06-18 10:43:00', '_uuid_cols': 'child_uid,school_name,child_age', 'rows': 200, '_uuid': 'bb8bb07c-7017-4e55-8c52-6463a32407b0'}, {'id': None, 'form_id': 'aser_001', 'survey_name': 'aser_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '01/01/2026 00:00', 'last_submission': '03/01/2026 00:00', 'logged_at': '2026-06-18 10:43:00', '_uuid_cols': 'child_uid,school_name,child_age', 'rows': 200, '_uuid': 'efb17d65-f889-45c8-984f-cea8cb8bd87b'}, {'id': None, 'form_id': 'aser_001', 'survey_name': 'aser_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '01/01/2026 00:00', 'last_submission': '03/01/2026 00:00', 'logged_at': '2026-06-18 10:43:00', '_uuid_cols': 'child_uid,school_name,child_age', 'rows': 200, '_uuid': '0ec04594-8857-43cd-91cf-c9f9c8c00bfa'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:44:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': 'f634067c-ca8f-47d1-9178-06dd0eccc28a'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:44:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': 'aa239c91-dfec-43ec-904f-b3aa149b42fc'}, {'id': None, 'form_id': 'aser_001', 'survey_name': 'aser_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '01/01/2026 00:00', 'last_submission': '03/01/2026 00:00', 'logged_at': '2026-06-18 10:56:00', '_uuid_cols': 'child_uid,school_name,child_age', 'rows': 200, '_uuid': 'd6fe9628-2466-4c82-bd26-3f90abff26cc'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:57:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': 'efacfaca-b0f2-4789-b7bc-41c73fe61caf'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:57:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': 'c6516267-2301-430f-89c4-a95b51efead7'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:58:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '3ea91f6e-271f-4c2e-97a5-b9283f30e39e'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:59:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '0151b701-fc87-443e-945d-573b1235948d'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:59:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '4dfc6064-9a08-4af4-a1c0-11ce0249d49c'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:59:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': 'f475e051-554d-4b34-802c-a78fcaf25847'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 10:59:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': 'f0f43a75-43aa-49df-9fe6-47f3b1633ad5'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 11:03:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': 'c7c64b0e-8913-448e-849c-1d838b43fbf8'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 11:04:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '85b0b40d-b4f4-49d2-a9b6-0cacbe4c7253'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 11:04:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': 'e0d998e5-4906-4fd0-a3b8-7e27670bf941'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-18 11:18:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '50ff9f3d-78e4-4ea2-9b76-d2559f52a051'}, {'id': None, 'form_id': 'aser_001', 'survey_name': 'aser_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '01/01/2026 00:00', 'last_submission': '03/01/2026 00:00', 'logged_at': '2026-06-18 11:19:00', '_uuid_cols': 'child_uid,school_name,child_age', 'rows': 200, '_uuid': 'a4d854a3-7b21-4992-9459-208fd10f5180'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-26 15:35:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': 'ec1bf9ce-38a0-49cd-be06-e1b0ae516a09'}, {'id': None, 'form_id': 'haldo_001', 'survey_name': 'haldo_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '11/04/2023 11:40', 'last_submission': '13/06/2023 12:27', 'logged_at': '2026-06-26 15:35:00', '_uuid_cols': 'start,end,childid', 'rows': 1246, '_uuid': '1500fb91-9ba4-48ce-b71f-0bb4167e2e33'}, {'id': None, 'form_id': 'aser_001', 'survey_name': 'aser_assessment', 'level': 'child', 'country': 'kenya', 'records_imported': None, 'first_submission': '01/01/2026 00:00', 'last_submission': '03/01/2026 00:00', 'logged_at': '2026-06-26 15:37:00', '_uuid_cols': 'child_uid,school_name,child_age', 'rows': 200, '_uuid': '78fcb899-ede7-4f01-bce2-7e86445fadf7'}], count=None)

In [56]:
indicators = pd.read_excel(r"C:\Users\F.Turner\Documents\MwM Proof of Concept V2\config\indicator_config.xlsx", sheet_name="Indicators")
calculations = pd.read_excel(r"C:\Users\F.Turner\Documents\MwM Proof of Concept V2\config\indicator_config.xlsx", sheet_name="Calculations")
components = pd.read_excel(r"C:\Users\F.Turner\Documents\MwM Proof of Concept V2\config\indicator_config.xlsx", sheet_name="Components")
domains = pd.read_excel(r"C:\Users\F.Turner\Documents\MwM Proof of Concept V2\config\indicator_config.xlsx", sheet_name="Domains")

In [72]:
dimensions = pd.read_excel(r"C:\Users\F.Turner\Documents\MwM Proof of Concept V2\config\Dimensions_config.xlsx", sheet_name="Dimensions")
columns = pd.read_excel(r"C:\Users\F.Turner\Documents\MwM Proof of Concept V2\config\Dimensions_config.xlsx", sheet_name="Columns")
values = pd.read_excel(r"C:\Users\F.Turner\Documents\MwM Proof of Concept V2\config\Dimensions_config.xlsx", sheet_name="Values")
operations = pd.read_excel(r"C:\Users\F.Turner\Documents\MwM Proof of Concept V2\config\Dimensions_config.xlsx", sheet_name="Operations")
bins = pd.read_excel(r"C:\Users\F.Turner\Documents\MwM Proof of Concept V2\config\Dimensions_config.xlsx", sheet_name="Bins")

In [76]:
tables = {
    "indicator_indicators": indicators, 
          "indicator_calculations": calculations, 
          "indicator_components": components, 
        #   "domains": domains,
          "dimensions": dimensions,
          "dimension_columns": columns,
          "dimension_values": values,
          "dimension_operations": operations,
          "dimension_bins": bins
          } 

for table_name, t in tables.items():
    t = t.replace({np.nan: None})
    records = t.to_dict(orient="records")
    print(table_name)
    print(len(records))
    print(records[:2])
    supabase.table(
        table_name
    ).upsert(
        records
    ).execute()

indicator_indicators
28
[{'id': 'haldo_self_concept', 'label': 'Haldo Self Concept', 'description': None, 'level': 'child', 'indicator_type': 'numeric', 'aggregation_type': 'calculated', 'aggregation_method': 'mean', 'missing_handling': 'ignore', 'active': True}, {'id': 'haldo_empathy', 'label': 'Haldo Empathy', 'description': None, 'level': 'child', 'indicator_type': 'numeric', 'aggregation_type': 'calculated', 'aggregation_method': 'mean', 'missing_handling': 'ignore', 'active': True}]
indicator_calculations
10
[{'indicator_id': 'haldo_self_concept', 'operation': 'mean', 'divide_by': None, 'rounding': None, 'notes': None}, {'indicator_id': 'haldo_empathy', 'operation': 'mean', 'divide_by': None, 'rounding': None, 'notes': None}]
indicator_components
36
[{'indicator_id': 'haldo_self_concept', 'component_name': 'selname', 'sort_order': 1}, {'indicator_id': 'haldo_self_concept', 'component_name': 'selage', 'sort_order': 2}]
dimensions
14
[{'id': 'date_time', 'dimension_type': 'ordinal', 'aggregation_method': 'last', 'display_order': 1, 'active': True}, {'id': 'admin0', 'dimension_type': 'categorical', 'aggregation_method': 'first', 'display_order': 2, 'active': True}]

APIError: {'message': 'permission denied for table dimensions', 'code': '42501', 'hint': 'Grant the required privileges to the current role with: GRANT SELECT, INSERT, UPDATE ON public.dimensions TO service_role;', 'details': None}